export type Product = {
  id: string;
  name: string;
  brand: string;
  category: string;
  categorySlug: string;
  price: number;
  oldPrice?: number;
  rating: number;
  reviews: number;
  image: string;
  gallery?: string[];
  badge?: "new" | "sale" | "bestseller";
  installments?: { count: number; value: number };
  freeShipping?: boolean;
  description?: string;
  specs?: Array<{ label: string; value: string }>;
  inStock?: number;
  colors?: Array<{ name: string; hex: string }>;
  sizes?: string[];
};

const img = (id: string) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=900&q=80`;

const inst = (price: number, count: number) => ({
  count,
  value: +(price / count).toFixed(2),
});

// Curated, confirmed-working Unsplash photo IDs grouped by theme
const PHOTOS = {
  // Eletrônicos
  headphones: "1505740420928-5e560c06d30e",
  smartwatch: "1523275335684-37898b6baf30",
  camera: "1606983340126-99ab4feaa64a",
  speaker: "1608043152269-423dbba4e7e1",
  keyboard: "1587829741301-dc798b83add3",
  laptop: "1496181133206-80ce9b88a853",
  console: "1486572788966-cfd3df1f5b42",
  earbuds: "1572569511127-92c50f4d3b5e",
  monitor: "1527443224154-c4a3942d3acf",
  tablet: "1561154464-82e9adf32764",
  phone: "1592750475338-74b7b21085ab",
  drone: "1507582020474-9a35b7d455d9",
  mouse: "1527864550417-7fd91fc51a46",
  // Moda
  jacket: "1551028719-00167b16eac5",
  tee: "1521572163474-6864f9cf17ab",
  fashion: "1490481651871-ab68de25d43d",
  jeans: "1542272604-787c3835535d",
  dress: "1539109136881-3be0616acf4b",
  hoodie: "1556821840-3a63f95609a7",
  shirt: "1602810318383-e386cc2a3ccf",
  // Calçados
  sneakerYellow: "1542291026-7eec264c27ff",
  sneakerWhite: "1595950653106-6c9ebd614d3a",
  bootBlack: "1520639888713-7851133b1ed0",
  sneakerCanvas: "1525966222134-fcfa99b8ae77",
  // Acessórios
  backpack: "1553062407-98eeb64c6a62",
  sunglasses: "1572635196237-14b3f281503f",
  bag: "1548036328-c9fa89d128fa",
  wallet: "1627123424574-724758594e93",
  cap: "1588850561407-ed78c282e89b",
  watch: "1524805444758-089113d48a6d",
  // Casa
  coffee: "1495474472287-4d71bcdd2085",
  lamp: "1513506003901-1e6a229e2d15",
  bedding: "1505691938895-1758d7feb511",
  sofa: "1555041469-a586c61ea9bc",
  airfryer: "1612883711226-0b3a89bbd0c1",
  // Beleza
  serum: "1556228720-195a672e8a03",
  perfume: "1541643600914-78b084683601",
  mask: "1571781926291-c477ebfd024b",
  lipstick: "1586495777744-4413f21062fa",
  kit: "1570172619644-dfd03ed5d881",
  perfumeMen: "1547887537-6158d64c35b3",
  brushes: "1487412947147-5cebf100ffc2",
} as const;

const baseProducts: Product[] = [
  // ============ ELETRÔNICOS ============
  {
    id: "e1",
    name: "Fone Bluetooth Cancelamento Ativo",
    brand: "Sonik",
    category: "Eletrônicos",
    categorySlug: "eletronicos",
    price: 899.0,
    oldPrice: 1299.0,
    rating: 4.9,
    reviews: 942,
    image: img(PHOTOS.headphones),
    gallery: [img(PHOTOS.headphones), img(PHOTOS.earbuds), img(PHOTOS.speaker)],
    badge: "bestseller",
    installments: inst(899, 12),
    freeShipping: true,
    description:
      "Headphone over-ear com cancelamento ativo de ruído de até 35dB. Bateria de 40h, conexão multipoint, drivers de 40mm com som hi-res e modo transparência.",
    specs: [
      { label: "Autonomia", value: "40h (ANC off) / 30h (ANC on)" },
      { label: "Conectividade", value: "Bluetooth 5.3 + USB-C" },
      { label: "Drivers", value: "40mm Hi-Res" },
      { label: "Peso", value: "248g" },
    ],
    inStock: 38,
    colors: [
      { name: "Preto", hex: "#0f172a" },
      { name: "Bege", hex: "#e7d9c4" },
    ],
  },
  {
    id: "e2",
    name: "Relógio Smart Series 8",
    brand: "Northwatch",
    category: "Eletrônicos",
    categorySlug: "eletronicos",
    price: 1599.0,
    oldPrice: 1899.0,
    rating: 4.7,
    reviews: 512,
    image: img(PHOTOS.smartwatch),
    gallery: [img(PHOTOS.smartwatch), img(PHOTOS.watch)],
    badge: "sale",
    installments: inst(1599, 12),
    freeShipping: true,
    inStock: 12,
  },
  {
    id: "e3",
    name: "Câmera Mirrorless 24MP + Lente Kit",
    brand: "Lensa",
    category: "Eletrônicos",
    categorySlug: "eletronicos",
    price: 4299.0,
    rating: 4.9,
    reviews: 156,
    image: img(PHOTOS.camera),
    badge: "new",
    installments: inst(4299, 12),
    freeShipping: true,
    inStock: 7,
  },
  {
    id: "e4",
    name: "Caixa de Som Portátil Beat 360",
    brand: "Sonik",
    category: "Eletrônicos",
    categorySlug: "eletronicos",
    price: 449.0,
    rating: 4.7,
    reviews: 289,
    image: img(PHOTOS.speaker),
    badge: "new",
    installments: inst(449, 8),
    inStock: 18,
  },
  {
    id: "e5",
    name: "Teclado Mecânico RGB Compact",
    brand: "PixelLab",
    category: "Eletrônicos",
    categorySlug: "eletronicos",
    price: 799.0,
    oldPrice: 999.0,
    rating: 4.9,
    reviews: 488,
    image: img(PHOTOS.keyboard),
    badge: "sale",
    installments: inst(799, 10),
    freeShipping: true,
    inStock: 22,
  },
  {
    id: "e6",
    name: "Smartphone Pro 256GB 5G",
    brand: "PixelLab",
    category: "Eletrônicos",
    categorySlug: "eletronicos",
    price: 5499.0,
    oldPrice: 6299.0,
    rating: 4.8,
    reviews: 1342,
    image: img(PHOTOS.phone),
    badge: "bestseller",
    installments: inst(5499, 12),
    freeShipping: true,
    inStock: 31,
  },
  {
    id: "e7",
    name: "Notebook Ultrafino 14” i7",
    brand: "PixelLab",
    category: "Eletrônicos",
    categorySlug: "eletronicos",
    price: 6899.0,
    oldPrice: 7999.0,
    rating: 4.7,
    reviews: 612,
    image: img(PHOTOS.laptop),
    badge: "sale",
    installments: inst(6899, 12),
    freeShipping: true,
    inStock: 9,
  },
  {
    id: "e8",
    name: "Mouse Sem Fio Ergonômico",
    brand: "PixelLab",
    category: "Eletrônicos",
    categorySlug: "eletronicos",
    price: 229.0,
    rating: 4.6,
    reviews: 1024,
    image: img(PHOTOS.mouse),
    installments: inst(229, 6),
    freeShipping: true,
    inStock: 76,
  },
  {
    id: "e9",
    name: "Monitor 27\" 4K IPS HDR",
    brand: "PixelLab",
    category: "Eletrônicos",
    categorySlug: "eletronicos",
    price: 2899.0,
    oldPrice: 3499.0,
    rating: 4.8,
    reviews: 318,
    image: img(PHOTOS.monitor),
    badge: "sale",
    installments: inst(2899, 12),
    freeShipping: true,
    inStock: 14,
  },
  {
    id: "e10",
    name: "Tablet Air 11\" 128GB Wi-Fi",
    brand: "PixelLab",
    category: "Eletrônicos",
    categorySlug: "eletronicos",
    price: 3299.0,
    rating: 4.7,
    reviews: 245,
    image: img(PHOTOS.tablet),
    installments: inst(3299, 12),
    freeShipping: true,
    inStock: 19,
  },
  {
    id: "e11",
    name: "Drone 4K com Estabilizador",
    brand: "Lensa",
    category: "Eletrônicos",
    categorySlug: "eletronicos",
    price: 3899.0,
    oldPrice: 4599.0,
    rating: 4.8,
    reviews: 187,
    image: img(PHOTOS.drone),
    badge: "sale",
    installments: inst(3899, 12),
    freeShipping: true,
    inStock: 8,
  },
  {
    id: "e12",
    name: "Fone Earbuds Pro com ANC",
    brand: "Sonik",
    category: "Eletrônicos",
    categorySlug: "eletronicos",
    price: 549.0,
    oldPrice: 749.0,
    rating: 4.8,
    reviews: 873,
    image: img(PHOTOS.earbuds),
    badge: "sale",
    installments: inst(549, 10),
    freeShipping: true,
    inStock: 64,
  },
  {
    id: "e13",
    name: "Console Gamer Edição Limitada",
    brand: "PixelLab",
    category: "Eletrônicos",
    categorySlug: "eletronicos",
    price: 4499.0,
    rating: 4.9,
    reviews: 1456,
    image: img(PHOTOS.console),
    badge: "bestseller",
    installments: inst(4499, 12),
    freeShipping: true,
    inStock: 5,
  },
  {
    id: "e14",
    name: "Smartwatch Sport GPS",
    brand: "Northwatch",
    category: "Eletrônicos",
    categorySlug: "eletronicos",
    price: 1199.0,
    oldPrice: 1499.0,
    rating: 4.6,
    reviews: 421,
    image: img(PHOTOS.watch),
    badge: "new",
    installments: inst(1199, 10),
    freeShipping: true,
    inStock: 17,
  },
  {
    id: "e15",
    name: "Câmera Vlog 4K Compacta",
    brand: "Lensa",
    category: "Eletrônicos",
    categorySlug: "eletronicos",
    price: 2199.0,
    rating: 4.7,
    reviews: 234,
    image: img(PHOTOS.camera),
    badge: "new",
    installments: inst(2199, 12),
    freeShipping: true,
    inStock: 11,
  },

  // ============ MODA ============
  {
    id: "m1",
    name: "Jaqueta Bomber Tech Fleece",
    brand: "Northbound",
    category: "Moda",
    categorySlug: "moda",
    price: 459.9,
    oldPrice: 599.9,
    rating: 4.7,
    reviews: 421,
    image: img(PHOTOS.jacket),
    badge: "sale",
    installments: inst(459.9, 10),
    inStock: 34,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "m2",
    name: "Camiseta Essential Premium",
    brand: "Northbound",
    category: "Moda",
    categorySlug: "moda",
    price: 129.9,
    rating: 4.6,
    reviews: 311,
    image: img(PHOTOS.tee),
    badge: "new",
    installments: inst(129.9, 4),
    inStock: 120,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "m3",
    name: "Calça Jeans Slim Wash",
    brand: "Northbound",
    category: "Moda",
    categorySlug: "moda",
    price: 249.9,
    oldPrice: 349.9,
    rating: 4.7,
    reviews: 587,
    image: img(PHOTOS.jeans),
    badge: "sale",
    installments: inst(249.9, 6),
    inStock: 73,
    sizes: ["38", "40", "42", "44", "46"],
  },
  {
    id: "m4",
    name: "Vestido Midi Plissado",
    brand: "Lumière",
    category: "Moda",
    categorySlug: "moda",
    price: 389.0,
    rating: 4.8,
    reviews: 156,
    image: img(PHOTOS.dress),
    badge: "new",
    installments: inst(389, 8),
    freeShipping: true,
    inStock: 28,
    sizes: ["P", "M", "G"],
  },
  {
    id: "m5",
    name: "Moletom Oversized Heavy",
    brand: "Northbound",
    category: "Moda",
    categorySlug: "moda",
    price: 329.9,
    oldPrice: 429.9,
    rating: 4.8,
    reviews: 692,
    image: img(PHOTOS.hoodie),
    badge: "bestseller",
    installments: inst(329.9, 8),
    inStock: 55,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "m6",
    name: "Casaco Trench Coat Bege",
    brand: "Lumière",
    category: "Moda",
    categorySlug: "moda",
    price: 749.0,
    oldPrice: 999.0,
    rating: 4.9,
    reviews: 92,
    image: img(PHOTOS.fashion),
    badge: "new",
    installments: inst(749, 12),
    freeShipping: true,
    inStock: 14,
    sizes: ["P", "M", "G"],
  },
  {
    id: "m7",
    name: "Camisa Linho Slim Fit",
    brand: "Northbound",
    category: "Moda",
    categorySlug: "moda",
    price: 279.9,
    rating: 4.6,
    reviews: 178,
    image: img(PHOTOS.shirt),
    installments: inst(279.9, 6),
    inStock: 36,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "m8",
    name: "Blusa Tricot Canelado",
    brand: "Lumière",
    category: "Moda",
    categorySlug: "moda",
    price: 199.9,
    oldPrice: 269.9,
    rating: 4.7,
    reviews: 234,
    image: img(PHOTOS.dress),
    badge: "sale",
    installments: inst(199.9, 6),
    inStock: 62,
    sizes: ["P", "M", "G"],
  },
  {
    id: "m9",
    name: "Polo Piquet Premium",
    brand: "Northbound",
    category: "Moda",
    categorySlug: "moda",
    price: 169.9,
    oldPrice: 219.9,
    rating: 4.6,
    reviews: 445,
    image: img(PHOTOS.tee),
    badge: "sale",
    installments: inst(169.9, 4),
    inStock: 110,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "m10",
    name: "Cardigã Lã Merino",
    brand: "Lumière",
    category: "Moda",
    categorySlug: "moda",
    price: 459.0,
    rating: 4.8,
    reviews: 67,
    image: img(PHOTOS.jacket),
    installments: inst(459, 10),
    freeShipping: true,
    inStock: 22,
    sizes: ["P", "M", "G"],
  },
  {
    id: "m11",
    name: "Shorts Tactel Esportivo",
    brand: "Northbound",
    category: "Moda",
    categorySlug: "moda",
    price: 149.0,
    rating: 4.5,
    reviews: 312,
    image: img(PHOTOS.jeans),
    installments: inst(149, 4),
    inStock: 88,
    sizes: ["P", "M", "G", "GG"],
  },
  {
    id: "m12",
    name: "Saia Midi Plissada",
    brand: "Lumière",
    category: "Moda",
    categorySlug: "moda",
    price: 259.0,
    rating: 4.5,
    reviews: 89,
    image: img(PHOTOS.fashion),
    installments: inst(259, 6),
    inStock: 41,
    sizes: ["P", "M", "G"],
  },

  // ============ CALÇADOS ============
  {
    id: "c1",
    name: "Tênis Runner Pro 3.0",
    brand: "AeroStep",
    category: "Calçados",
    categorySlug: "calcados",
    price: 499.9,
    oldPrice: 749.9,
    rating: 4.8,
    reviews: 1284,
    image: img(PHOTOS.sneakerYellow),
    gallery: [
      img(PHOTOS.sneakerYellow),
      img(PHOTOS.sneakerWhite),
      img(PHOTOS.sneakerCanvas),
    ],
    badge: "sale",
    installments: inst(499.9, 10),
    freeShipping: true,
    description:
      "Tênis com tecnologia de amortecimento avançada para corridas longas. Cabedal respirável, solado em borracha de alta aderência e palmilha responsiva.",
    specs: [
      { label: "Material", value: "Mesh respirável + EVA" },
      { label: "Drop", value: "8mm" },
      { label: "Peso", value: "265g (40)" },
      { label: "Indicação", value: "Asfalto e esteira" },
    ],
    inStock: 24,
    colors: [
      { name: "Preto", hex: "#0f172a" },
      { name: "Branco", hex: "#f8fafc" },
      { name: "Coral", hex: "#fb7185" },
    ],
    sizes: ["38", "39", "40", "41", "42", "43"],
  },
  {
    id: "c2",
    name: "Tênis Casual Classic White",
    brand: "AeroStep",
    category: "Calçados",
    categorySlug: "calcados",
    price: 329.9,
    rating: 4.6,
    reviews: 873,
    image: img(PHOTOS.sneakerWhite),
    installments: inst(329.9, 6),
    freeShipping: true,
    inStock: 41,
    sizes: ["38", "39", "40", "41", "42", "43"],
  },
  {
    id: "c3",
    name: "Bota Coturno Couro Premium",
    brand: "Lumière",
    category: "Calçados",
    categorySlug: "calcados",
    price: 689.0,
    oldPrice: 899.0,
    rating: 4.8,
    reviews: 187,
    image: img(PHOTOS.bootBlack),
    badge: "sale",
    installments: inst(689, 10),
    freeShipping: true,
    inStock: 14,
    sizes: ["38", "39", "40", "41", "42", "43"],
  },
  {
    id: "c4",
    name: "Tênis Skate Canvas",
    brand: "AeroStep",
    category: "Calçados",
    categorySlug: "calcados",
    price: 259.9,
    oldPrice: 339.9,
    rating: 4.6,
    reviews: 521,
    image: img(PHOTOS.sneakerCanvas),
    badge: "sale",
    installments: inst(259.9, 6),
    inStock: 78,
    sizes: ["37", "38", "39", "40", "41", "42", "43"],
  },
  {
    id: "c5",
    name: "Tênis Performance Trail",
    brand: "AeroStep",
    category: "Calçados",
    categorySlug: "calcados",
    price: 599.0,
    oldPrice: 799.0,
    rating: 4.8,
    reviews: 256,
    image: img(PHOTOS.sneakerYellow),
    badge: "sale",
    installments: inst(599, 10),
    freeShipping: true,
    inStock: 17,
    sizes: ["39", "40", "41", "42", "43"],
  },
  {
    id: "c6",
    name: "Sneaker Retrô Color Block",
    brand: "AeroStep",
    category: "Calçados",
    categorySlug: "calcados",
    price: 449.0,
    rating: 4.7,
    reviews: 412,
    image: img(PHOTOS.sneakerWhite),
    badge: "new",
    installments: inst(449, 8),
    inStock: 33,
    sizes: ["37", "38", "39", "40", "41", "42"],
  },
  {
    id: "c7",
    name: "Tênis High Top Branco",
    brand: "AeroStep",
    category: "Calçados",
    categorySlug: "calcados",
    price: 389.0,
    rating: 4.7,
    reviews: 645,
    image: img(PHOTOS.sneakerCanvas),
    badge: "bestseller",
    installments: inst(389, 8),
    inStock: 52,
    sizes: ["37", "38", "39", "40", "41", "42"],
  },
  {
    id: "c8",
    name: "Chuteira Society Pro",
    brand: "AeroStep",
    category: "Calçados",
    categorySlug: "calcados",
    price: 459.0,
    rating: 4.8,
    reviews: 312,
    image: img(PHOTOS.sneakerYellow),
    installments: inst(459, 8),
    freeShipping: true,
    inStock: 21,
    sizes: ["38", "39", "40", "41", "42", "43"],
  },
  {
    id: "c9",
    name: "Mocassim Couro Bordado",
    brand: "Lumière",
    category: "Calçados",
    categorySlug: "calcados",
    price: 549.0,
    rating: 4.7,
    reviews: 78,
    image: img(PHOTOS.bootBlack),
    badge: "new",
    installments: inst(549, 10),
    freeShipping: true,
    inStock: 19,
    sizes: ["38", "39", "40", "41", "42", "43"],
  },
  {
    id: "c10",
    name: "Sandália Plataforma Verão",
    brand: "Lumière",
    category: "Calçados",
    categorySlug: "calcados",
    price: 289.0,
    rating: 4.5,
    reviews: 96,
    image: img(PHOTOS.sneakerWhite),
    installments: inst(289, 6),
    inStock: 49,
    sizes: ["34", "35", "36", "37", "38", "39"],
  },
  {
    id: "c11",
    name: "Sapatênis Couro Casual",
    brand: "Lumière",
    category: "Calçados",
    categorySlug: "calcados",
    price: 379.0,
    oldPrice: 499.0,
    rating: 4.6,
    reviews: 134,
    image: img(PHOTOS.bootBlack),
    badge: "sale",
    installments: inst(379, 8),
    inStock: 27,
    sizes: ["38", "39", "40", "41", "42", "43"],
  },
  {
    id: "c12",
    name: "Sapatilha Tricot Comfort",
    brand: "Lumière",
    category: "Calçados",
    categorySlug: "calcados",
    price: 199.0,
    rating: 4.5,
    reviews: 89,
    image: img(PHOTOS.sneakerCanvas),
    installments: inst(199, 4),
    inStock: 64,
    sizes: ["34", "35", "36", "37", "38"],
  },

  // ============ ACESSÓRIOS ============
  {
    id: "a1",
    name: "Mochila Urban 25L Impermeável",
    brand: "Carry&Co",
    category: "Acessórios",
    categorySlug: "acessorios",
    price: 289.9,
    rating: 4.6,
    reviews: 318,
    image: img(PHOTOS.backpack),
    installments: inst(289.9, 6),
    freeShipping: true,
    inStock: 56,
  },
  {
    id: "a2",
    name: "Óculos de Sol Aviador Premium",
    brand: "Lumière",
    category: "Acessórios",
    categorySlug: "acessorios",
    price: 349.0,
    oldPrice: 459.0,
    rating: 4.5,
    reviews: 207,
    image: img(PHOTOS.sunglasses),
    badge: "sale",
    installments: inst(349, 6),
    inStock: 21,
  },
  {
    id: "a3",
    name: "Bolsa Tiracolo Couro Légère",
    brand: "Lumière",
    category: "Acessórios",
    categorySlug: "acessorios",
    price: 689.0,
    rating: 4.8,
    reviews: 142,
    image: img(PHOTOS.bag),
    badge: "new",
    installments: inst(689, 10),
    freeShipping: true,
    inStock: 9,
  },
  {
    id: "a4",
    name: "Carteira Slim em Couro Italiano",
    brand: "Carry&Co",
    category: "Acessórios",
    categorySlug: "acessorios",
    price: 229.0,
    oldPrice: 299.0,
    rating: 4.7,
    reviews: 415,
    image: img(PHOTOS.wallet),
    badge: "sale",
    installments: inst(229, 6),
    inStock: 73,
  },
  {
    id: "a5",
    name: "Boné Snapback Logo Bordado",
    brand: "Northbound",
    category: "Acessórios",
    categorySlug: "acessorios",
    price: 119.9,
    rating: 4.6,
    reviews: 528,
    image: img(PHOTOS.cap),
    badge: "bestseller",
    installments: inst(119.9, 4),
    inStock: 134,
  },
  {
    id: "a6",
    name: "Relógio Analógico Couro",
    brand: "Northwatch",
    category: "Acessórios",
    categorySlug: "acessorios",
    price: 489.0,
    oldPrice: 649.0,
    rating: 4.7,
    reviews: 287,
    image: img(PHOTOS.watch),
    badge: "sale",
    installments: inst(489, 8),
    freeShipping: true,
    inStock: 25,
  },
  {
    id: "a7",
    name: "Mochila Notebook Anti-furto",
    brand: "Carry&Co",
    category: "Acessórios",
    categorySlug: "acessorios",
    price: 379.0,
    rating: 4.8,
    reviews: 631,
    image: img(PHOTOS.backpack),
    badge: "bestseller",
    installments: inst(379, 8),
    freeShipping: true,
    inStock: 42,
  },
  {
    id: "a8",
    name: "Bolsa Transversal Mini",
    brand: "Lumière",
    category: "Acessórios",
    categorySlug: "acessorios",
    price: 459.0,
    rating: 4.6,
    reviews: 178,
    image: img(PHOTOS.bag),
    badge: "new",
    installments: inst(459, 8),
    inStock: 18,
  },
  {
    id: "a9",
    name: "Óculos Redondo Acetato",
    brand: "Lumière",
    category: "Acessórios",
    categorySlug: "acessorios",
    price: 279.0,
    oldPrice: 379.0,
    rating: 4.5,
    reviews: 134,
    image: img(PHOTOS.sunglasses),
    badge: "sale",
    installments: inst(279, 6),
    inStock: 36,
  },
  {
    id: "a10",
    name: "Cinto Couro Fivela Premium",
    brand: "Lumière",
    category: "Acessórios",
    categorySlug: "acessorios",
    price: 189.0,
    rating: 4.5,
    reviews: 96,
    image: img(PHOTOS.wallet),
    installments: inst(189, 4),
    inStock: 48,
  },
  {
    id: "a11",
    name: "Pochete Tactel Esportiva",
    brand: "Carry&Co",
    category: "Acessórios",
    categorySlug: "acessorios",
    price: 99.9,
    rating: 4.4,
    reviews: 423,
    image: img(PHOTOS.backpack),
    installments: inst(99.9, 4),
    inStock: 88,
  },
  {
    id: "a12",
    name: "Cachecol Lã Tricolor",
    brand: "Northbound",
    category: "Acessórios",
    categorySlug: "acessorios",
    price: 159.0,
    rating: 4.6,
    reviews: 67,
    image: img(PHOTOS.cap),
    installments: inst(159, 4),
    inStock: 53,
  },

  // ============ CASA & DECOR ============
  {
    id: "h1",
    name: "Cafeteira Espresso Automática",
    brand: "Domestika",
    category: "Casa & Decor",
    categorySlug: "casa-decor",
    price: 2199.0,
    oldPrice: 2799.0,
    rating: 4.8,
    reviews: 142,
    image: img(PHOTOS.coffee),
    badge: "sale",
    installments: inst(2199, 12),
    freeShipping: true,
    inStock: 14,
  },
  {
    id: "h2",
    name: "Luminária Pendente Minimal",
    brand: "Domestika",
    category: "Casa & Decor",
    categorySlug: "casa-decor",
    price: 389.0,
    rating: 4.5,
    reviews: 67,
    image: img(PHOTOS.lamp),
    installments: inst(389, 6),
    inStock: 28,
  },
  {
    id: "h3",
    name: "Sofá Modular 3 Lugares",
    brand: "Domestika",
    category: "Casa & Decor",
    categorySlug: "casa-decor",
    price: 4899.0,
    oldPrice: 6299.0,
    rating: 4.7,
    reviews: 89,
    image: img(PHOTOS.sofa),
    badge: "sale",
    installments: inst(4899, 12),
    freeShipping: true,
    inStock: 6,
  },
  {
    id: "h4",
    name: "Air Fryer Digital 5L",
    brand: "Domestika",
    category: "Casa & Decor",
    categorySlug: "casa-decor",
    price: 599.0,
    oldPrice: 799.0,
    rating: 4.9,
    reviews: 1872,
    image: img(PHOTOS.airfryer),
    badge: "bestseller",
    installments: inst(599, 10),
    freeShipping: true,
    inStock: 47,
  },
  {
    id: "h5",
    name: "Edredom Queen Microfibra",
    brand: "Domestika",
    category: "Casa & Decor",
    categorySlug: "casa-decor",
    price: 459.0,
    oldPrice: 599.0,
    rating: 4.7,
    reviews: 421,
    image: img(PHOTOS.bedding),
    badge: "sale",
    installments: inst(459, 8),
    inStock: 56,
  },
  {
    id: "h6",
    name: "Jogo de Panelas Antiaderente 7pç",
    brand: "Domestika",
    category: "Casa & Decor",
    categorySlug: "casa-decor",
    price: 899.0,
    rating: 4.6,
    reviews: 312,
    image: img(PHOTOS.coffee),
    badge: "bestseller",
    installments: inst(899, 10),
    freeShipping: true,
    inStock: 38,
  },
  {
    id: "h7",
    name: "Liquidificador Inox 1200W",
    brand: "Domestika",
    category: "Casa & Decor",
    categorySlug: "casa-decor",
    price: 449.0,
    oldPrice: 599.0,
    rating: 4.6,
    reviews: 256,
    image: img(PHOTOS.airfryer),
    badge: "sale",
    installments: inst(449, 8),
    inStock: 31,
  },
  {
    id: "h8",
    name: "Mesa Lateral Madeira Carvalho",
    brand: "Domestika",
    category: "Casa & Decor",
    categorySlug: "casa-decor",
    price: 549.0,
    rating: 4.5,
    reviews: 78,
    image: img(PHOTOS.sofa),
    installments: inst(549, 10),
    inStock: 18,
  },
  {
    id: "h9",
    name: "Tapete Geométrico 2x3m",
    brand: "Domestika",
    category: "Casa & Decor",
    categorySlug: "casa-decor",
    price: 689.0,
    rating: 4.7,
    reviews: 134,
    image: img(PHOTOS.bedding),
    badge: "new",
    installments: inst(689, 10),
    freeShipping: true,
    inStock: 22,
  },
  {
    id: "h10",
    name: "Cafeteira French Press Inox",
    brand: "Domestika",
    category: "Casa & Decor",
    categorySlug: "casa-decor",
    price: 259.0,
    rating: 4.6,
    reviews: 178,
    image: img(PHOTOS.coffee),
    installments: inst(259, 6),
    inStock: 64,
  },
  {
    id: "h11",
    name: "Luminária de Mesa LED Dimerizável",
    brand: "Domestika",
    category: "Casa & Decor",
    categorySlug: "casa-decor",
    price: 329.0,
    oldPrice: 429.0,
    rating: 4.6,
    reviews: 156,
    image: img(PHOTOS.lamp),
    badge: "sale",
    installments: inst(329, 6),
    inStock: 27,
  },
  {
    id: "h12",
    name: "Jogo de Lençóis Queen 400 Fios",
    brand: "Domestika",
    category: "Casa & Decor",
    categorySlug: "casa-decor",
    price: 389.0,
    rating: 4.8,
    reviews: 412,
    image: img(PHOTOS.bedding),
    badge: "new",
    installments: inst(389, 6),
    inStock: 96,
  },

  // ============ BELEZA ============
  {
    id: "b1",
    name: "Sérum Facial Vitamina C 20%",
    brand: "GlowLab",
    category: "Beleza",
    categorySlug: "beleza",
    price: 159.9,
    oldPrice: 199.0,
    rating: 4.9,
    reviews: 1872,
    image: img(PHOTOS.serum),
    badge: "bestseller",
    installments: inst(159.9, 4),
    freeShipping: true,
    inStock: 86,
  },
  {
    id: "b2",
    name: "Perfume Floral 100ml EDP",
    brand: "Lumière",
    category: "Beleza",
    categorySlug: "beleza",
    price: 459.0,
    rating: 4.7,
    reviews: 244,
    image: img(PHOTOS.perfume),
    badge: "new",
    installments: inst(459, 10),
    inStock: 32,
  },
  {
    id: "b3",
    name: "Kit Hidratante Facial Pro",
    brand: "GlowLab",
    category: "Beleza",
    categorySlug: "beleza",
    price: 289.0,
    oldPrice: 379.0,
    rating: 4.8,
    reviews: 567,
    image: img(PHOTOS.kit),
    badge: "sale",
    installments: inst(289, 6),
    freeShipping: true,
    inStock: 64,
  },
  {
    id: "b4",
    name: "Batom Matte Long Lasting",
    brand: "Lumière",
    category: "Beleza",
    categorySlug: "beleza",
    price: 89.9,
    rating: 4.7,
    reviews: 1432,
    image: img(PHOTOS.lipstick),
    badge: "bestseller",
    installments: inst(89.9, 3),
    inStock: 248,
  },
  {
    id: "b5",
    name: "Máscara Facial Detox 50ml",
    brand: "GlowLab",
    category: "Beleza",
    categorySlug: "beleza",
    price: 119.0,
    rating: 4.6,
    reviews: 312,
    image: img(PHOTOS.mask),
    installments: inst(119, 4),
    inStock: 89,
  },
  {
    id: "b6",
    name: "Perfume Masculino Amadeirado 100ml",
    brand: "Lumière",
    category: "Beleza",
    categorySlug: "beleza",
    price: 549.0,
    oldPrice: 729.0,
    rating: 4.9,
    reviews: 187,
    image: img(PHOTOS.perfumeMen),
    badge: "sale",
    installments: inst(549, 10),
    freeShipping: true,
    inStock: 22,
  },
  {
    id: "b7",
    name: "Pincéis Maquiagem 12 Peças",
    brand: "Lumière",
    category: "Beleza",
    categorySlug: "beleza",
    price: 199.0,
    oldPrice: 269.0,
    rating: 4.8,
    reviews: 245,
    image: img(PHOTOS.brushes),
    badge: "sale",
    installments: inst(199, 4),
    inStock: 58,
  },
  {
    id: "b8",
    name: "Shampoo Reconstrutor 500ml",
    brand: "GlowLab",
    category: "Beleza",
    categorySlug: "beleza",
    price: 109.0,
    oldPrice: 149.0,
    rating: 4.6,
    reviews: 478,
    image: img(PHOTOS.serum),
    badge: "sale",
    installments: inst(109, 3),
    inStock: 156,
  },
  {
    id: "b9",
    name: "Protetor Solar FPS 60 Toque Seco",
    brand: "GlowLab",
    category: "Beleza",
    categorySlug: "beleza",
    price: 89.9,
    rating: 4.7,
    reviews: 921,
    image: img(PHOTOS.mask),
    badge: "bestseller",
    installments: inst(89.9, 3),
    inStock: 234,
  },
  {
    id: "b10",
    name: "Base Líquida Cobertura Natural",
    brand: "Lumière",
    category: "Beleza",
    categorySlug: "beleza",
    price: 149.0,
    rating: 4.6,
    reviews: 387,
    image: img(PHOTOS.kit),
    installments: inst(149, 4),
    inStock: 112,
  },
  {
    id: "b11",
    name: "Paleta de Sombras 24 Cores",
    brand: "Lumière",
    category: "Beleza",
    categorySlug: "beleza",
    price: 189.0,
    rating: 4.8,
    reviews: 692,
    image: img(PHOTOS.brushes),
    badge: "new",
    installments: inst(189, 4),
    inStock: 73,
  },
  {
    id: "b12",
    name: "Difusor Aromático 200ml",
    brand: "Lumière",
    category: "Beleza",
    categorySlug: "beleza",
    price: 139.0,
    rating: 4.5,
    reviews: 156,
    image: img(PHOTOS.perfume),
    installments: inst(139, 4),
    inStock: 67,
  },
];

export const allProducts: Product[] = baseProducts;
export const products: Product[] = baseProducts
  .filter((p) => p.badge === "bestseller" || p.rating >= 4.8)
  .slice(0, 10);
export const newArrivals: Product[] = baseProducts
  .filter((p) => p.badge === "new")
  .slice(0, 5);

export function getProduct(id: string): Product | undefined {
  return baseProducts.find((p) => p.id === id);
}

export function getProductsByCategory(slug: string): Product[] {
  return baseProducts.filter((p) => p.categorySlug === slug);
}

export function getOnSale(): Product[] {
  return baseProducts.filter((p) => p.oldPrice && p.oldPrice > p.price);
}

export function getBestsellers(): Product[] {
  return [...baseProducts].sort((a, b) => b.reviews - a.reviews).slice(0, 16);
}

export function getNew(): Product[] {
  return baseProducts.filter((p) => p.badge === "new");
}

export type Category = {
  name: string;
  slug: string;
  image: string;
  count: number;
  description: string;
  hero: string;
};

export const categories: Category[] = [
  {
    name: "Eletrônicos",
    slug: "eletronicos",
    image: img(PHOTOS.headphones),
    hero: img(PHOTOS.keyboard),
    count: 1240,
    description:
      "Smartphones, fones, smartwatches, câmeras e mais — tecnologia premium para o seu dia a dia.",
  },
  {
    name: "Moda",
    slug: "moda",
    image: img(PHOTOS.fashion),
    hero: img(PHOTOS.fashion),
    count: 2310,
    description:
      "Peças versáteis e atemporais para construir um guarda-roupa autêntico.",
  },
  {
    name: "Calçados",
    slug: "calcados",
    image: img(PHOTOS.sneakerYellow),
    hero: img(PHOTOS.sneakerYellow),
    count: 980,
    description: "Tênis, sapatos e sandálias selecionados das melhores marcas.",
  },
  {
    name: "Acessórios",
    slug: "acessorios",
    image: img(PHOTOS.backpack),
    hero: img(PHOTOS.backpack),
    count: 1432,
    description: "Mochilas, óculos, relógios e detalhes que completam o look.",
  },
  {
    name: "Casa & Decor",
    slug: "casa-decor",
    image: img(PHOTOS.bedding),
    hero: img(PHOTOS.bedding),
    count: 870,
    description: "Móveis, iluminação, eletros e decoração para uma casa com personalidade.",
  },
  {
    name: "Beleza",
    slug: "beleza",
    image: img(PHOTOS.serum),
    hero: img(PHOTOS.serum),
    count: 612,
    description: "Skincare, maquiagem e perfumes — beleza com curadoria.",
  },
];

export function getCategory(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export const brands = [
  "AeroStep",
  "Sonik",
  "Northwatch",
  "Carry&Co",
  "Lumière",
  "Lensa",
  "Northbound",
  "PixelLab",
  "Domestika",
  "GlowLab",
];

export function formatBRL(value: number): string {
  return value.toLocaleString("pt-BR", {
    style: "currency",
    currency: "BRL",
  });
}
